import type { Config } from "tailwindcss";
import tailwindAnimate from "tailwindcss-animate";

export default {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
		"./SCREENS/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			colors: {
				/* ── MD3 / Stitch design tokens ── */
				"background": "#fcf9f8",
				"on-surface-variant": "#43474f",
				"tertiary-container": "#004033",
				"surface-bright": "#fcf9f8",
				"on-secondary": "#ffffff",
				"deep-navy": "#00081C",
				"on-secondary-fixed": "#2b1700",
				"secondary-fixed-dim": "#ffb869",
				"surface-dim": "#dcd9d8",
				"primary-fixed-dim": "#a5c8ff",
				"surface-container": "#f0edec",
				"on-error-container": "#93000a",
				"secondary-container": "#fdad4e",
				"inverse-primary": "#a5c8ff",
				"on-secondary-fixed-variant": "#673d00",
				"tertiary": "#00281f",
				"on-tertiary-container": "#6fad9a",
				"on-secondary-container": "#704200",
				"error-red": "#BA1A1A",
				"tertiary-fixed": "#b0efdb",
				"teal-accent": "#00A4A6",
				"on-background": "#1b1c1b",
				"error": "#ba1a1a",
				"on-tertiary": "#ffffff",
				"on-tertiary-fixed": "#002019",
				"surface-container-high": "#eae7e7",
				"error-container": "#ffdad6",
				"on-tertiary-fixed-variant": "#095041",
				"primary-container": "#00386b",
				"surface-container-lowest": "#ffffff",
				"inverse-surface": "#303030",
				"surface-tint": "#376095",
				"outline-variant": "#c3c6d1",
				"on-error": "#ffffff",
				"inverse-on-surface": "#f3f0ef",
				"primary-fixed": "#d4e3ff",
				"on-primary": "#ffffff",
				"on-primary-fixed": "#001c3a",
				"tertiary-fixed-dim": "#94d3bf",
				"on-primary-fixed-variant": "#1b487b",
				"outline": "#737780",
				"secondary-fixed": "#ffdcbb",
				"on-surface": "#1b1c1b",
				"surface-container-low": "#f6f3f2",
				"sidebar-bg": "#F6F3F2",
				"secondary": "#885200",
				"surface-variant": "#e4e2e1",
				"surface-container-highest": "#e4e2e1",
				"on-primary-container": "#7ca3dc",

				/* ── shadcn/ui + legacy school colors ── */
				"school-blue": "var(--school-blue)",
				"school-blue-light": "var(--school-blue-light)",
				"school-blue-dark": "var(--school-blue-dark)",
				"school-amber": "var(--school-amber)",
				"school-teal": "var(--school-teal)",
				"school-coral": "var(--school-coral)",
				"school-purple": "var(--school-purple)",
				"school-green": "var(--school-green)",
				"text-primary": "var(--text-primary)",
				"text-secondary": "var(--text-secondary)",
				"text-tertiary": "var(--text-tertiary)",
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "#002246",
					foreground: "hsl(var(--primary-foreground))",
				},
				surface: {
					DEFAULT: "#fcf9f8",
				},
				secondary: {
					DEFAULT: "#885200",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
			},
			fontFamily: {
				sans: ["Plus Jakarta Sans", "var(--font-sans)", "system-ui", "sans-serif"],
				"body-lg": ["Plus Jakarta Sans"],
				"body-md": ["Plus Jakarta Sans"],
				"headline-lg-mobile": ["Plus Jakarta Sans"],
				"code": ["Plus Jakarta Sans"],
				"headline-xl": ["Plus Jakarta Sans"],
				"headline-lg": ["Plus Jakarta Sans"],
				"label-md": ["Plus Jakarta Sans"],
				"headline-md": ["Plus Jakarta Sans"],
			},
			fontSize: {
				"body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
				"body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
				"headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
				"code": ["13px", { lineHeight: "18px", fontWeight: "500" }],
				"headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
				"headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
				"label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
				"headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
				xs: ["12px", "1.5"],
				sm: ["14px", "1.5"],
				base: ["16px", "1.6"],
				lg: ["18px", "1.6"],
				xl: ["20px", "1.4"],
				"2xl": ["24px", "1.2"],
				"3xl": ["30px", "1.2"],
			},
			borderRadius: {
				sm: "var(--radius-sm)",
				DEFAULT: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			spacing: {
				"margin-desktop": "32px",
				"container-max": "1440px",
				"margin-mobile": "16px",
				"gutter": "24px",
				"base-unit": "4px",
				"1": "var(--spacing-1, 4px)",
				"2": "var(--spacing-2, 8px)",
				"3": "var(--spacing-3, 12px)",
				"4": "var(--spacing-4, 16px)",
				"6": "var(--spacing-6, 24px)",
				"8": "var(--spacing-8, 32px)",
				"12": "var(--spacing-12, 48px)",
				"16": "var(--spacing-16, 64px)",
			},
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
		},
	},
	plugins: [tailwindAnimate],
} satisfies Config;
